// <auto-generated />
using BirdAPI_lab4.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BirdAPI_lab4.Migrations
{
    [DbContext(typeof(BirdFarmDbContext))]
    [Migration("20251125183203_Lab4_Changes")]
    partial class Lab4_Changes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.25");

            modelBuilder.Entity("BirdAPI_lab4.Models.Bird", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Birds");
                });

            modelBuilder.Entity("BirdAPI_lab4.Models.Egg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BirdId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BirdId");

                    b.ToTable("Eggs");
                });

            modelBuilder.Entity("BirdAPI_lab4.Models.Egg", b =>
                {
                    b.HasOne("BirdAPI_lab4.Models.Bird", "Bird")
                        .WithMany("Eggs")
                        .HasForeignKey("BirdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bird");
                });

            modelBuilder.Entity("BirdAPI_lab4.Models.Bird", b =>
                {
                    b.Navigation("Eggs");
                });
#pragma warning restore 612, 618
        }
    }
}
